import { useTranslations } from '../languages';

const t = useTranslations('cardTemplates')();

export const cardTemplates = {
  timeline: {
    title: t.timeline.title,
    subtitle: t.timeline.subtitle,
    text: t.timeline.text,
    image: t.timeline.image,
    icon: t.timeline.icon,
    elevation: t.timeline.elevation,
    padding: t.timeline.padding,
    rounded: t.timeline.rounded,
    loading: t.timeline.loading,
    disabled: t.timeline.disabled,
    showButtons: t.timeline.showButtons,
    buttonText: t.timeline.buttonText,
    buttonWidth: t.timeline.buttonWidth,
    buttonPosition: t.timeline.buttonPosition,
    showProgress: t.timeline.showProgress,
    variant: t.timeline.variant,
    color: t.timeline.color,
    buttonVariant: t.timeline.buttonVariant,
    buttonColor: t.timeline.buttonColor,
    progressSize: t.timeline.progressSize,
    progressColor: t.timeline.progressColor,
    showTimeline: t.timeline.showTimeline,
    showSparkline: t.timeline.showSparkline
  },

  weather: {
    title: t.weather.title,
    subtitle: t.weather.subtitle,
    text: t.weather.text,
    image: t.weather.image,
    icon: t.weather.icon,
    elevation: t.weather.elevation,
    padding: t.weather.padding,
    rounded: t.weather.rounded,
    loading: t.weather.loading,
    disabled: t.weather.disabled,
    showButtons: t.weather.showButtons,
    buttonText: t.weather.buttonText,
    buttonWidth: t.weather.buttonWidth,
    buttonPosition: t.weather.buttonPosition,
    showProgress: t.weather.showProgress,
    variant: t.weather.variant,
    color: t.weather.color,
    buttonVariant: t.weather.buttonVariant,
    buttonColor: t.weather.buttonColor,
    progressSize: t.weather.progressSize,
    progressColor: t.weather.progressColor,
    showTimeline: t.weather.showTimeline,
    showSparkline: t.weather.showSparkline,
    sparklineData: t.weather.sparklineData,
    sparklineLabels: t.weather.sparklineLabels,
    sparklineShowLabels: t.weather.sparklineShowLabels,
    sparklineLineWidth: t.weather.sparklineLineWidth,
    sparklineColor: t.weather.sparklineColor,
    sparklineGradient: t.weather.sparklineGradient
  },

  statistics: {
    title: t.statistics.title,
    subtitle: t.statistics.subtitle,
    text: t.statistics.text,
    image: t.statistics.image,
    icon: t.statistics.icon,
    elevation: t.statistics.elevation,
    padding: t.statistics.padding,
    rounded: t.statistics.rounded,
    loading: t.statistics.loading,
    disabled: t.statistics.disabled,
    showButtons: t.statistics.showButtons,
    buttonText: t.statistics.buttonText,
    buttonWidth: t.statistics.buttonWidth,
    buttonPosition: t.statistics.buttonPosition,
    showProgress: t.statistics.showProgress,
    showTimeline: t.statistics.showTimeline,
    showSparkline: t.statistics.showSparkline,
    sparklineType: t.statistics.sparklineType,
    sparklineData: t.statistics.sparklineData,
    sparklineColor: t.statistics.sparklineColor,
    sparklineHeight: t.statistics.sparklineHeight,
    sparklineLabelSize: t.statistics.sparklineLabelSize,
    sparklineShowValue: t.statistics.sparklineShowValue,
    sparklineLabels: t.statistics.sparklineLabels,
    sparklineShowLabels: t.statistics.sparklineShowLabels,
    sparklineLineWidth: t.statistics.sparklineLineWidth,
    sparklineGradient: t.statistics.sparklineGradient
  },

  file: {
    title: t.file.title,
    subtitle: t.file.subtitle,
    text: t.file.text,
    image: t.file.image,
    icon: t.file.icon,
    variant: t.file.variant,
    color: t.file.color,
    elevation: t.file.elevation,
    padding: t.file.padding,
    rounded: t.file.rounded,
    loading: t.file.loading,
    disabled: t.file.disabled,
    showButtons: t.file.showButtons,
    buttonText: t.file.buttonText,
    buttonVariant: t.file.buttonVariant,
    buttonColor: t.file.buttonColor,
    buttonWidth: t.file.buttonWidth,
    buttonPosition: t.file.buttonPosition,
    buttonIcon: t.file.buttonIcon,
    showProgress: t.file.showProgress,
  }
};

export const getCardTemplate = (templateName: string) => {
  return JSON.parse(JSON.stringify(cardTemplates[templateName as keyof typeof cardTemplates] || {}));
};

